kind: Deployment
apiVersion: apps/v1
metadata:
  name: streamlit-client
  labels:
    app: streamlit-client
    app.kubernetes.io/component: streamlit-client
    app.kubernetes.io/instance: streamlit-client
    app.kubernetes.io/name: streamlit-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-client
  template:
    metadata:
      labels:
        app: streamlit-client
        deployment: streamlit-client
    spec:
      containers:
        - name: streamlit-client
          image: 'quay.io/michaelclifford/streamlit_client:0.1.0'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8501
              protocol: TCP
          imagePullPolicy: IfNotPresent


