apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: github-mcp-server-v1
  namespace: llama-serve
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: github-mcp-server-v1
  namespace: llama-serve
spec:
  output:
    to:
      kind: ImageStreamTag
      name: github-mcp-server-v1:latest
  source:
    git:
      uri: https://github.com/anyuzoey/servers.git
      ref: main
    contextDir: "." 
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: src/github/Dockerfile
      noCache: true
      forcePull: true
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
      
