apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-mcp-server1
  namespace: llama-serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-mcp-server1
  template:
    metadata:
      labels:
        app: github-mcp-server1
    spec:
      containers:
      - name: github-mcp-server1
        image: quay.io/rh-ee-yuan/github_mcp_server:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          npx -y supergateway --stdio "node dist/index.js" --port 8080
        ports:
        - containerPort: 8080
        env:
        - name: NPM_CONFIG_CACHE
          value: /tmp/.npm
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-credentials-v1
              key: token
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: github-mcp-server1
  namespace: llama-serve
spec:
  selector:
    app: github-mcp-server1
  ports:
  - port: 80
    targetPort: 8080
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: github-mcp-server1
  namespace: llama-serve
spec:
  to:
    kind: Service
    name: github-mcp-server1
  port:
    targetPort: 8080
    