apiVersion: v1
kind: Service
metadata:
  name: ansible-mcp-server
  namespace: llama-serve
spec:
  selector:
    app: ansible-mcp-server
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
